apiVersion: v1
kind: Pod
metadata:
  name: kaniko
  labels:
    name: kaniko
spec:
  containers:
  - image: gcr.io/kaniko-project/executor:latest
    name: kaniko
    args:
        - "--dockerfile=Dockerfile"
        - "--context=git://github.com/ashoksiva59/reactfiori.git"
        - "--destination=ashoksiva59/sapreactfiori-image:latest"
    ports:
    - containerPort: 3306
      name: kaniko
    volumeMounts:
    - name: kaniko-secret
      mountPath: /kaniko/.docker
  restartPolicy : Never
  volumes:
  - name: kaniko-secret
    secret:
      secretName: doeckerregcred
      items:
        - key: .dockerconfigjson
          path: config.json
  

